### ISSUE TITLE
Issue with Running Pandas in WebAssembly Environment Using Componentize-Py

### ISSUE THREAD

**Issue by cihansakman** [dicej/wasi-wheels#7]
Hello all, thank you so much for your intensive work to bring native libraries into Python. I was also working on these to give it a try but unfortunately, I couldn't reproduce the whole package. Even before that, some of the libraries you provided as .tar.gz as the latest releases don't work properly. For pandas, it doesn't recognize the following symbols:

```
        /0/pandas/_libs/window/aggregations.cpython-312-wasm32-wasi.so needs __cxa_allocate_exception (function [I32] -> [I32])
        /0/pandas/_libs/window/aggregations.cpython-312-wasm32-wasi.so needs __cxa_throw (function [I32, I32, I32] -> [])
```

I have created stubs to workaround this with the following:
```
// stubs.c
#include <stdint.h>

// Stub for __cxa_allocate_exception
__attribute__((import_name("__cxa_allocate_exception")))
uint32_t __cxa_allocate_exception(uint32_t size) {
    return 0;  // Return 0 as a placeholder
}

// Stub for __cxa_throw
__attribute__((import_name("__cxa_throw")))
void __cxa_throw(uint32_t exception, uint32_t typeinfo, uint32_t destructor) {
    //nothing to return
    
}

```
and compiled it into a wasm-wasi static library and added to my LDFLAGs. I'm not sure if this approach even makes sense but after the compilation process is done on the componentize-py I didn't get the same error. Instead, I got the dependency errors:

```
AssertionError: Traceback (most recent call last):
  File "/0/app.py", line 3, in <module>
    import pandas as pd
  File "/0/pandas/__init__.py", line 19, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
pytz: No module named 'pytz'
dateutil: No module named 'dateutil'


Caused by:
    ImportError: Unable to import required dependencies:
    pytz: No module named 'pytz'
    dateutil: No module named 'dateutil'
```

When I installed the dependencies to venv where componentize-py also runs this time I got another problem:

```
  File "/0/app.py", line 3, in <module>
    import pandas as pd
  File "/0/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/0/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/0/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/0/pandas/_libs/tslibs/__init__.py", line 40, in <module>
    from pandas._libs.tslibs.conversion import localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "pandas/_libs/tslibs/tzconversion.pyx", line 55, in init pandas._libs.tslibs.tzconversion
ValueError: Buffer dtype mismatch, expected 'const int64_t' but got 'long long'


Caused by:
    ValueError: Buffer dtype mismatch, expected 'const int64_t' but got 'long long'
```

I think this occurs because of the versioning problems. Could you give some updates about the last status? I was following the numpy example from [matrix-math exaple](https://github.com/bytecodealliance/componentize-py/tree/main/examples/matrix-math). Numpy does run without any problem but pandas do not. I use the *wasm-sdk* and *Cpython* from the submodules of the wasi-wheels repo and `wasmtime 27.0.0 (8eefa236f 2024-11-20)` for wasmtime-cli. Following are the python libs and versions:

```
componentize-py==0.16.0
importlib_resources==6.4.5
python-dateutil==2.9.0.post0
pytz==2024.2
six==1.16.0
wasmtime==27.0.2
```

**Comment by cihansakman** [comment]
Here is my build script as well

```
#!/bin/bash

BUILD_DIR="$(realpath ../build)"
WASI_SDK_PATH="${BUILD_DIR}/wasi-sdk"
CROSS_PREFIX="$(realpath ../cpython/builddir/wasi/install)"

set -eou pipefail



if [ ! -e venv ]; then
  python3.12 -m venv venv
fi

. venv/bin/activate
pip install build wheel setuptools meson[ninja]==1.2.1 meson-python==0.13.1 versioneer[toml] 'numpy<2' Cython==3.0.5


# Patch numpy to add WASM support in the correct location
# Search for the line 'define NPY_CPU_AMD64' and add wasm target to npy_cpu header
sed -i '/#define NPY_CPU_AMD64/a\
#elif defined(__wasm__) || defined(__wasm32__)\
    #define NPY_CPU_WASM' venv/lib/python3.12/site-packages/numpy/core/include/numpy/npy_cpu.h



# Truly, the "Good Code"
#
# Turn off setjmp instructions because we don't have access to them under WASI.
# Ideally we'd be compiling pandas' copy of numpy against the WASI numpy we've
# already built, but it seems like pandas is set up to compile against a local,
# import-able copy of numpy instead.
cat >venv/lib/python3.12/site-packages/numpy/core/include/numpy/npy_interrupt.h <<'EOF'

#ifndef NUMPY_CORE_INCLUDE_NUMPY_NPY_INTERRUPT_H_
#define NUMPY_CORE_INCLUDE_NUMPY_NPY_INTERRUPT_H_


#define NPY_SIGINT_ON
#define NPY_SIGINT_OFF

#endif  /* NUMPY_CORE_INCLUDE_NUMPY_NPY_INTERRUPT_H_ */
EOF

ARCH_TRIPLET=_wasi_wasm32-wasi

export CC="${WASI_SDK_PATH}/bin/clang"
export CXX="${WASI_SDK_PATH}/bin/clang++"

export PYTHONPATH=$CROSS_PREFIX/lib/python3.12

export CFLAGS="-I${CROSS_PREFIX}/include/python3.12 -D__EMSCRIPTEN__=1"
export CXXFLAGS="-I${CROSS_PREFIX}/include/python3.12"
export LDSHARED=${CC}
export AR="${WASI_SDK_PATH}/bin/ar"
export RANLIB=true
export LDFLAGS="-shared /home/cihan/wasm_examples/wasi-wheels/pandas/libstubs.a"
export _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_${ARCH_TRIPLET}
export NPY_DISABLE_SVML=1
export NPY_BLAS_ORDER=
export NPY_LAPACK_ORDER=
export NPY_NO_SIGNAL=1
export MACOSX_DEPLOYMENT_TARGET=3.11

cd src
python3 setup.py build -j 4 --verbose
# wheel unpack --dest build dist/*.whl 

# Verify dependencies are bundled
if [ $? -eq 0 ]; then
    echo "Build completed successfully.
else
    echo "Build failed." >&2
    exit 1
fi
```

**Comment by dicej** [comment]
Hi @cihansakman.  Thanks for reporting this.

To my knowledge, nobody has managed to run Pandas on WASI successfully.  [Chris Dickinson's PR](https://github.com/dicej/wasi-wheels/pull/1) to add support for building it and other packages includes instructions for stubbing out the `__cxa_*` functions as you discovered, but that isn't sufficient to actually run it.

[This conversation](https://bytecodealliance.zulipchat.com/#narrow/channel/219900-wasi/topic/Attempting.20to.20use.20pandas.20with.20componentize-py) covers our last serious attempt, which also failed.  My understanding is that Pandas relies on Cython, which requires C++ exception handling support, which requires WebAssembly exception handling support, and that's not yet widely supported on WASI-capable runtimes (e.g. Wasmtime).  There may also be other issues such as the transitive dependency problems you encountered (which may require those dependencies to be built for WASI also).

I don't know how much work will be required to support Pandas on WASI -- only that it's more than I (or anyone else) has been able to devote to it so far.  Please let us know if you have any success!

**Comment by cihansakman** [comment]
Thank you for the quick response, @dicej. Now it's clearer to me. Maybe I can suggest a PR to patch adding the wasm target to the pandas copy of NumPy's npy_cpu header with the following in bash: during the compilation, it throws an unknown CPU error.

```
# Patch numpy to add WASM support in the correct location
# Search for the line 'define NPY_CPU_AMD64' and add wasm target to npy_cpu header
sed -i '/#define NPY_CPU_AMD64/a\
#elif defined(__wasm__) || defined(__wasm32__)\
    #define NPY_CPU_WASM' venv/lib/python3.12/site-packages/numpy/core/include/numpy/npy_cpu.h
```
